services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ki-frontend
    environment:
      - VIRTUAL_HOST=hki-itk.wynz.site,www.hki-itk.wynz.site
      - VIRTUAL_PORT=5173
      - LETSENCRYPT_HOST=hki-itk.wynz.site,www.hki-itk.wynz.site
      - LETSENCRYPT_EMAIL=septianushendra3@gmail.com
    restart: always
    networks: 
      - proxy-network
networks:
  proxy-network:
    external: true
