services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ki-frontend

    volumes:
      - frontend-build:/app/dist
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8034:80"
      - "8035:443"
    volumes:
      - frontend-build:/usr/share/nginx/html:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

volumes:
  frontend-build:
